//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenelRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Genel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Genel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinavGorevlendirme.Resources.Genel", typeof(Genel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetli.
        /// </summary>
        public static string Hizmetli {
            get {
                return ResourceManager.GetString("Hizmetli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal Edilen Sınavlar.
        /// </summary>
        public static string IptalEdilenSinav {
            get {
                return ResourceManager.GetString("IptalEdilenSinav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string IptalEdilenSinavKisa {
            get {
                return ResourceManager.GetString("IptalEdilenSinavKisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müdür.
        /// </summary>
        public static string Mudur {
            get {
                return ResourceManager.GetString("Mudur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müdür Yardımcısı.
        /// </summary>
        public static string MudurYardimcisi {
            get {
                return ResourceManager.GetString("MudurYardimcisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen.
        /// </summary>
        public static string Ogretmen {
            get {
                return ResourceManager.GetString("Ogretmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmamış Sınavlar.
        /// </summary>
        public static string OnaylanmamisSinav {
            get {
                return ResourceManager.GetString("OnaylanmamisSinav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmadı.
        /// </summary>
        public static string OnaylanmamisSinavKisa {
            get {
                return ResourceManager.GetString("OnaylanmamisSinavKisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmış Sınavlar.
        /// </summary>
        public static string OnaylanmisSinav {
            get {
                return ResourceManager.GetString("OnaylanmisSinav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylandı.
        /// </summary>
        public static string OnaylanmisSinavKisa {
            get {
                return ResourceManager.GetString("OnaylanmisSinavKisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şöför.
        /// </summary>
        public static string Sofor {
            get {
                return ResourceManager.GetString("Sofor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıyıcı.
        /// </summary>
        public static string Tasiyici {
            get {
                return ResourceManager.GetString("Tasiyici", resourceCulture);
            }
        }
    }
}
