//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SG_DAL.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string basarili_durum {
            get {
                return ResourceManager.GetString("basarili_durum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarı ile gerçekleşti.
        /// </summary>
        public static string basarili_kayit {
            get {
                return ResourceManager.GetString("basarili_kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girmiş olduğunuz Meb Kodu sistemde kayıtlı.
        /// </summary>
        public static string hata_ayniMebKoduSistemdeMevcut {
            get {
                return ResourceManager.GetString("hata_ayniMebKoduSistemdeMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girmiş olduğunuz okul adı sistemde kayıtlı.
        /// </summary>
        public static string hata_ayniOkulSistemdeMevcut {
            get {
                return ResourceManager.GetString("hata_ayniOkulSistemdeMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı TC kimlik numaralı kişi sistemde kayıtlı.
        /// </summary>
        public static string hata_ayniTcSistemdeMevcut {
            get {
                return ResourceManager.GetString("hata_ayniTcSistemdeMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string hatali_durum {
            get {
                return ResourceManager.GetString("hatali_durum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sırasında hata oluştu.
        /// </summary>
        public static string hatali_kayit {
            get {
                return ResourceManager.GetString("hatali_kayit", resourceCulture);
            }
        }
    }
}
